version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_local
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/var/jenkins_home/workspace
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

volumes:
  jenkins_home:
